server:
  port: 9090

spring:
  application:
    name: msvc-service
  config:
    import: optional:configserver:http://localhots:8888
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: ips_app_test
      schema-action: create-if-not-exists
      username: cassandra
      password: cassandra

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      service-url:
        defaultZone: http://localhost:8761/eureka